CREATE TABLE [dbo].[PurchaseOrderImportItems] (
    [ItemID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [ImportID]        BIGINT         NOT NULL,
    [Agy]             NVARCHAR (50)  NULL,
    [AppropFund]      NVARCHAR (50)  NULL,
    [AgyFund]         NVARCHAR (50)  NULL,
    [AgyFundTitle]    NVARCHAR (50)  NULL,
    [CompSourceGroup] NVARCHAR (50)  NULL,
    [OrgCode1]        NVARCHAR (50)  NULL,
    [PONumber]        NVARCHAR (50)  NULL,
    [RefSfx]          NVARCHAR (50)  NULL,
    [VoucherDOcVP]    NVARCHAR (50)  NULL,
    [VendorName]      NVARCHAR (500) NULL,
    [POAdjustment]    NVARCHAR (50)  NULL,
    [POADJAMT]        FLOAT (53)     NULL,
    [POAMT]           FLOAT (53)     NULL,
    [VOUCHERAMT]      FLOAT (53)     NULL,
    [POBAL]           FLOAT (53)     NULL,
    [InvoiceNo]       NVARCHAR (50)  NULL,
    [CheckNo]         NVARCHAR (50)  NULL,
    [PaymentDate]     DATETIME       NULL,
    [FISCAL_YEAR]     FLOAT (53)     NULL,
    [EffDate]         DATETIME       NULL,
    [ProjectNo]       NVARCHAR (50)  NULL,
    [ProjectPh]       NVARCHAR (50)  NULL,
    [ProjectTitle]    NVARCHAR (50)  NULL,
    [LastProcDate]    DATETIME       NULL,
    [AppropYear]      FLOAT (53)     NULL,
    [CompGLAcct]      NVARCHAR (50)  NULL,
    [TCode]           NVARCHAR (50)  NULL,
    [RefDoc]          NVARCHAR (50)  NULL,
    [AgyGLAcct]       NVARCHAR (50)  NULL,
    [IndexCode]       NVARCHAR (50)  NULL,
    [IndexCodeTitle]  NVARCHAR (500) NULL,
    [PCA]             NVARCHAR (50)  NULL,
    [PCATitle]        NVARCHAR (500) NULL,
    [CompObject]      NVARCHAR (50)  NULL,
    [PrimaryDocKey]   NVARCHAR (50)  NULL,
    [PrimaryDocSfx]   NVARCHAR (50)  NULL,
    [CreatedDate]     DATETIME       NOT NULL,
    [UpdatedDate]     DATETIME       NULL,
    CONSTRAINT [PK_PurchaseOrderImportItems] PRIMARY KEY CLUSTERED ([ItemID] ASC),
    CONSTRAINT [FK_PurchaseOrderImportItems_PurchaseOrderImports] FOREIGN KEY ([ImportID]) REFERENCES [dbo].[PurchaseOrderImports] ([ImportID])
);

