//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRIFACT.DCCouncil.NPS.Web.Portal.Pages.SiteAdministration {
    
    
    public partial class UserManagement {
        
        /// <summary>
        /// UserManagementCtrl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PRIFACT.DCCouncil.NPS.Web.Portal.UserCtrls.SiteAdministration.UserManagementCtrl UserManagementCtrl1;
    }
}
